// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: list.sql

package db

import (
	"context"
	"time"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (
    name,
    user_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, created_at, updated_at, user_id
`

type CreateListParams struct {
	Name      string
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRowContext(ctx, createList,
		arg.Name,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getlist = `-- name: Getlist :one
SELECT id, name, created_at, updated_at, user_id FROM lists WHERE id = $1
`

func (q *Queries) Getlist(ctx context.Context, id int32) (List, error) {
	row := q.db.QueryRowContext(ctx, getlist, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listlists = `-- name: Listlists :many
SELECT id, name, created_at, updated_at, user_id FROM lists ORDER BY name
`

func (q *Queries) Listlists(ctx context.Context) ([]List, error) {
	rows, err := q.db.QueryContext(ctx, listlists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
