// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) (Item, error)
	DeleteItemRelations(ctx context.Context, itemID int32) ([]ListItem, error)
	DeleteList(ctx context.Context, arg DeleteListParams) (List, error)
	GetItemsByListName(ctx context.Context, id int32) ([]Item, error)
	GetListForUpdate(ctx context.Context, arg GetListForUpdateParams) (List, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	Getitem(ctx context.Context, id int32) (Item, error)
	Getlist(ctx context.Context, arg GetlistParams) (List, error)
	Getlists(ctx context.Context, userID int32) ([]List, error)
	LinkItemToList(ctx context.Context, arg LinkItemToListParams) (ListItem, error)
	Listusers(ctx context.Context) ([]User, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	// NO KEY : avoid dead-lock !
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
}

var _ Querier = (*Queries)(nil)
