// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteList(ctx context.Context, arg DeleteListParams) (List, error)
	GetListForUpdate(ctx context.Context, arg GetListForUpdateParams) (List, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	Getitem(ctx context.Context, id int32) (Item, error)
	Getlist(ctx context.Context, id int32) (List, error)
	Getlists(ctx context.Context, userID int32) ([]List, error)
	ListItems(ctx context.Context) ([]Item, error)
	Listusers(ctx context.Context) ([]User, error)
	// NO KEY : avoid dead-lock !
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
}

var _ Querier = (*Queries)(nil)
